name: Alpine build
run-name: Alpine build
on:
  push:
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare
    runs-on: docker
    uses: actions/pmbootstrap-build/.forgejo/workflows/prepare.yaml@v1

  build:
    name: Build for ${{ matrix.arch }}
    runs-on: docker
    needs: prepare
    uses: actions/pmbootstrap-build/.forgejo/workflows/build.yaml@v1
    strategy:
      matrix:
        arch:
          - x86_64
          - x86
          - aarch64
          - armv7
          - riscv64
    with:
      name: singularity
      aports: package/alpine
      arch: ${{ matrix.arch }}
      src: .
      time: ${{ needs.prepare.outputs.time }}
      submodules: recursive

  upload:
    name: Upload
    needs: build
    runs-on: docker
    uses: actions/upload-alpine-package/.forgejo/workflows/upload-artifacts.yaml@main
    secrets: inherit
